# Generated by Django 6.0.1 on 2026-01-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Prioridad de la alerta', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], help_text='Estado de la alerta', max_length=15),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(help_text='Título de la alerta', max_length=255),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Indica si la evidencia ya fue revisada'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='source',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('web', 'Web'), ('agent', 'Agent')], help_text='Fuente de la evidencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='summary',
            field=models.CharField(help_text='Resumen de la evidencia', max_length=255),
        ),
    ]
