# Generated by Django 6.0.1 on 2026-01-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_severity_alter_alert_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alert',
            table='tb_alerts',
        ),
        migrations.AlterModelTable(
            name='evidence',
            table='tb_evidences',
        ),
    ]
